name: Run Playwright UI tests
on:
  workflow_dispatch: # Manually trigger the workflow
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV
          echo "TESTS=${{ secrets.TESTS }}" >> $GITHUB_ENV
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> $GITHUB_ENV
          echo "REPORTER=${{ secrets.REPORTER }}" >> $GITHUB_ENV
          echo "API_CLIENT=${{ secrets.API_CLIENT }}" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Install browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright UI tests
        run: npm run test:ui
        continue-on-error: true

      # Create Allure report
      - name: Create Allure report
        run: npm run report-create

      - name: Save Allure report
        uses: actions/upload-artifact@v2
        with:
          name: api-report
          path: src/report/allure-report
